const GLOBAL_ETRANSFER_EMAIL = "habman61@gmail.com"; 

const defaultCampsites = [
    // B Section
    { id: "B1", name: "Billy & Heather", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B2", name: "Riley & Mac", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B3", name: "Paul & Lucy", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B4", name: "Candy & Greg", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B5", name: "Joe & Nancy", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B6", name: "Chris", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B7", name: "Wendy & Ian", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B8", name: "Laurie & Bodo", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B9", name: "Tammy & Gerald", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B10", name: "Nadia & Stephan", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B11", name: "Julie & Stephane", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B12", name: "Danielle & Christian", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B13", name: "Brandon & Mellisa", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B14", name: "Deanna & Drew", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B15", name: "Andy & Kelly", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B16", name: "Devin & Blair", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "B17", name: "Jenn & Marcel", visited: false, doNotBother: false, purchaseType: null, amount: null },

    // L Section
    { id: "L1", name: "Louise & Alain", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "L2", name: "Steve", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "L3", name: "Randy & Carolyn", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "L4", name: "Brian & Maryanne", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "L5", name: "Shannon & Adam", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "L6", name: "Christine & Kevin", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "L7", name: "Jason & Karine", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "L8", name: "Ashley & Matt", visited: false, doNotBother: false, purchaseType: null, amount: null },

    // P Section
    { id: "P1", name: "Ann & Martin", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P2", name: "Louise & Chuck", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P3", name: "Ellen & Alec", visited: false, doNotBother: true, purchaseType: null, amount: null },
    { id: "P4", name: "Tammy & Eddie", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P5", name: "Ellie & Ernie", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P6", name: "Ian & Jo-ann", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P7", name: "Wendy & Murray", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P8", name: "Rhonda & Steve", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P9", name: "Vacant", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P10", name: "Marina", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P11", name: "Doug & Kathleen", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P12", name: "Tammy & Russ", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P13", name: "Tim & Tara", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P14", name: "Sue & Duke", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P15", name: "Tina & Serge", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P16", name: "Johanna", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P17", name: "Neil & Naz", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P18", name: "Nathalie & Claude", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P19", name: "Valerie B.", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P20", name: "Joan & Doug", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P21", name: "Jason Gray", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P22", name: "Remi & Sylvie", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P23", name: "Doug & Karen", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P25", name: "Belinda & Sam", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P26", name: "Joanne & Chris & Josee", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P27", name: "Tedra & Clayton", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P28", name: "Nina & Kris", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P29", name: "Megan & Stephan", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P30", name: "Fiona & Ed", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P31", name: "Jenn & Mike", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P32", name: "Roma & Garry", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P33", name: "Lori & Rob", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P34", name: "Karen", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P35", name: "Brenda & Judy", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P36", name: "Marilyn & Jason", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P37", name: "Shawn & Amanda", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P38", name: "Ryan-Angela-Rob", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P39", name: "Danielle & Angi", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P40", name: "Angie-Brittany-Braydon", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P41", name: "Pat & Goldie", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P44", name: "Debbie & George", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P45/P46", name: "Doug & Lena", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P47", name: "Richard & Jo-Anne", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P49", name: "Ryan & Linda", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P50", name: "Heaven & Jeff", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P51", name: "Jessica & Zack", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P52", name: "Kathy & Eugene - PAID FOR SEASON", visited: false, doNotBother: true, purchaseType: null, amount: null },
    { id: "P53", name: "Nelson & Ann", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P54", name: "Colin & Tracey", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P55", name: "Lorraine & Les", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P56", name: "Diane & Al", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "P57", name: "Annie & Collin", visited: false, doNotBother: false, purchaseType: null, amount: null },

    // S Section
    { id: "S1", name: "Don & Julie", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S2", name: "Angie & Pat", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S3", name: "Steve & Caroline", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S4", name: "Wade & Monique", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S5", name: "Sonya & Colin", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S6", name: "Paula & Peter", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S8", name: "Dan & Maureen", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S9", name: "Dave", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S10", name: "Joann & Alain", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S11", name: "Tim & Laurie", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S12", name: "Rob & Kerry", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S13", name: "Debbie & Doug", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S14", name: "Diane & Carl", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S15", name: "Elizabeth", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S16", name: "Antoniette & Antonio", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S17", name: "Pat & Barry", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S18", name: "Dave & Sandra", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S19", name: "Tony & Louise", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S20", name: "Stephanie & Ken", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S21", name: "Taylor", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S22", name: "Janet & Randy", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S23", name: "Brian & Wendy", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S24", name: "Sarah & Steve", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S25", name: "Betty & David", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S26", name: "Dan & Sue", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S27", name: "Lloyd", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S28", name: "Nadine", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S29", name: "Steven & Julie", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S30", name: "Greg & Cathy", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S31", name: "Kelly", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S32", name: "Derek & Colleen", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S33", name: "Karla & Peter", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S34", name: "Colleen & Andre", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S35", name: "James & Ella", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "S36", name: "Kate & Matt", visited: false, doNotBother: false, purchaseType: null, amount: null },

    // T Section
    { id: "T1", name: "Natalie & Christian", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "T2", name: "Martine & Maurice", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "T3", name: "Sylvie & Scott", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "T4/T5", name: "Shirley & Roger", visited: false, doNotBother: false, purchaseType: null, amount: null },
    { id: "T6", name: "Michael & Diane", visited: false, doNotBother: false, purchaseType: null, amount: null }
];
